data:
  market_end: '15:30'
  market_start: 09:15
  selection_minutes: 10
  selection_time: 09:25
  timeframe_primary: 10T
  timeframe_secondary: 1H
  top_stocks_count: 10
indicators:
  ema_fast: 3
  ema_slow: 10
  ema_trend: 50
  rsi_overbought: 60
  rsi_oversold: 30
  rsi_period: 14
strategy:
  base_capital: 1000000
  profit_target: 0.02
  profit_trail_start: 0.005
  risk_per_trade: 0.005
  stop_loss: 0.005
  trailing_stop: 0.0075
